all:
	g++ main.cpp init.cpp bitboards.cpp hashkeys.cpp board.cpp data.cpp attack.cpp io.cpp makemove.cpp movegen.cpp uci.cpp validate.cpp -o ChessEngine.exe
	ChessEngine.exe
# CCWIN=x86_64-w64-mingw32-gcc
# CFLAGS=-O2 -Wall -std=c99