all:
	g++ main.cpp init.cpp bitboards.cpp hashkeys.cpp board.cpp data.cpp attack.cpp io.cpp movegen.cpp validate.cpp makemove.cpp perft.cpp search.cpp misc.cpp pvtable.cpp evaluate.cpp uci.cpp -o ChessEngine
	./ChessEngine

# CCWIN=x86_64-w64-mingw32-gcc
# CFLAGS=-O2 -Wall -std=c99