all:
g++ main.cpp init.cpp psqt.cpp evaluation_type.cpp attack_gen.cpp eval_info.cpp bitboards.cpp zobrist.cpp pawn_analysis.cpp board.cpp -o ChessEngine
# CCWIN=x86_64-w64-mingw32-gcc
# CFLAGS=-O2 -Wall -std=c99